spring.application.name=movie-catalog-service-config-server-test
server.port=8084
eureka.client.serviceUrl.defaultZone=http://localhost:8762/eureka/
eureka.client.should-unregister-on-shutdown=true
management.endpoints.web.exposure.include=hystrix.stream
hystrix.dashboard.proxyStreamAllowList=*
